// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloWorld.proto

package com.grpc.demoGRPC.demoGRPC.grpc.stub;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.demoGRPC.demoGRPC.grpc.stub.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
